### ISSUE TITLE
Does this work for windows containers, in windows OS

### ISSUE THREAD

**Issue by amccool** [larsks/undocker#18]
using powershell I cant tell if
`docker pull <image> | undocker -o <image>`

is working.   

`undocker --help` works fine.   but I cant tell if the | (pipe) in powershell is working properly

**Comment by amccool** [comment]
here's the output from the blog sample, under windows 10 powershell


```
PS C:\Users\XXXX> docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox
697743189b6d: Pull complete
Digest: sha256:061ca9704a714ee3e8b80523ec720c64f6209ad3f97c0ff7cb9ec7d19f15149f
Status: Downloaded newer image for busybox:latest
PS C:\Users\XXXX> docker save busybox | C:\Python27\Scripts\undocker.exe -o busy
Traceback (most recent call last):
  File "C:\Python27\Scripts\undocker-script.py", line 11, in <module>
    load_entry_point('undocker==5', 'console_scripts', 'undocker')()
  File "c:\python27\lib\site-packages\undocker.py", line 108, in main
    repos = img.extractfile('repositories')
  File "c:\python27\lib\tarfile.py", line 2145, in extractfile
    tarinfo = self.getmember(member)
  File "c:\python27\lib\tarfile.py", line 1827, in getmember
    tarinfo = self._getmember(name)
  File "c:\python27\lib\tarfile.py", line 2396, in _getmember
    members = self.getmembers()
  File "c:\python27\lib\tarfile.py", line 1838, in getmembers
    self._load()        # all members, we first have to
  File "c:\python27\lib\tarfile.py", line 2419, in _load
    tarinfo = self.next()
  File "c:\python27\lib\tarfile.py", line 2352, in next
    raise ReadError("unexpected end of data")
tarfile.ReadError: unexpected end of data
```
