### ISSUE TITLE
Images may be bigger than available memory

### ISSUE THREAD

**Issue by temoto** [larsks/undocker#2]
```
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "/home/core/bin/undocker.py", line 125, in <module>
    main()
  File "/home/core/bin/undocker.py", line 70, in main
    fd.write(sys.stdin.read())
MemoryError
```

**Comment by temoto** [comment]
Thank you so much!

**Comment by amccool** [comment]
sorry to late post, but this appears to be a problem still on windows
32gb laptop.  powershell topped out at 31.9 gb

```
PS C:\Users\XXX\Downloads\docker> docker save microsoft/dotnet-framework-samples:latest | C:\Python27\Scripts\undocker.exe -o microsoft/dotnet-framework-samples:latest
Program 'undocker.exe' failed to run: Insufficient memory to continue the execution of the program.At line:1 char:57
+ ... es:latest | C:\Python27\Scripts\undocker.exe -o microsoft/dotnet-fram ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ docker save microsoft/dotnet-framework-samples:latest | C:\Python27\S ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```
