### ISSUE TITLE
Getting IsADirectoryError when trying to run examples

### ISSUE THREAD

**Issue by charles-l** [larsks/undocker#22]
`undocker -i -o` seems to be broken.

When I try to run the example from the README:

```
% docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox
Digest: sha256:a9286defaba7b3a519d585ba0e37d0b2cbee74ebfe590960b0b1d6a5e97d1e1d
Status: Image is up to date for busybox:latest
docker.io/library/busybox:latest
% docker save busybox | undocker -i -o busybox busybox
Traceback (most recent call last):
  File "/home/nc/.local/bin/undocker", line 8, in <module>
    sys.exit(main())
  File "/home/nc/.local/lib/python3.8/site-packages/undocker.py", line 99, in main
    open(args.image, 'rb') if args.image
IsADirectoryError: [Errno 21] Is a directory: 'busybox'
```

Running `undocker` 7:

```
% pip3 show undocker
Name: undocker
Version: 7
Summary: Unpack docker images
Home-page: http://github.com/larsks/undocker
Author: Lars Kellogg-Stedman
Author-email: lars@oddbit.com
License: UNKNOWN
Location: /home/nc/.local/lib/python3.8/site-packages
Requires:
Required-by:
```

**Comment by charles-l** [comment]
Ohh just checked the code. It looks like no argument is required when reading from `stdin` anymore? I've just tested it and it seems to work. I'll update the error message to clarify that a bit more...
