### ISSUE TITLE
Too many levels of symbolic links

### ISSUE THREAD

**Issue by temoto** [larsks/undocker#3]
I'm looking for guidance on how to debug where is the problem and work around it.

The image is debian:8 with many packages installed, including tzdata. Also, it's indeterministic, It always fails on different symlinks.

```
root=/media/data/infra-state
rm -rf $root
mkdir $root
cd $root
docker save ${name} |sudo ~/bin/python ~/bin/undocker.py --output .

Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "/home/core/bin/undocker.py", line 129, in <module>
    main()
  File "/home/core/bin/undocker.py", line 125, in main
    layer.extractall(path=args.output)
  File "/home/core/pypy/lib-python/2.7/tarfile.py", line 2070, in extractall
    self.extract(tarinfo, path)
  File "/home/core/pypy/lib-python/2.7/tarfile.py", line 2107, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/home/core/pypy/lib-python/2.7/tarfile.py", line 2183, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/home/core/pypy/lib-python/2.7/tarfile.py", line 2223, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 40] Too many levels of symbolic links: './usr/share/zoneinfo/Australia/Broken_Hill'

# It extracted
$ sudo ls -lh /media/data/infra-state/usr/share/zoneinfo/Australia/ |fgrep -i 'broken_hill'
lrwxrwxrwx  1 root root   10 Apr 22 01:34 Broken_Hill -> Yancowinna
lrwxrwxrwx  1 root root   11 Apr 22 01:34 Yancowinna -> Broken_Hill

# Here's what is supposed to be in image (maybe it's only correctly constructed by another layer):
$ docker run --rm -it infra-state ls -lh /usr/share/zoneinfo/Australia/ |egrep 'Broken_Hill|Yancowinna'
-rw-r--r--  8 root root 2.2K Apr 14 14:50 Broken_Hill
lrwxrwxrwx  1 root root   11 Apr 14 14:50 Yancowinna -> Broken_Hill
```

**Comment by larsks** [comment]
Does that happen with the plain `debian:8` image?  If not, can you post a minimum reproducer so I can test it locally? Thanks!

**Comment by temoto** [comment]
It doesn't reproduce on plain debian:8 or the one with additional /usr/share/zoneinfo copied from problematic image. I'll try to make minimum reproducer again some time later.

**Comment by temoto** [comment]
Turns out, I've ran out of inodes and then some other issue with host filesystem.
