### ISSUE TITLE
KeyError: "filename 'repositories' not found"

### ISSUE THREAD

**Issue by austinc88** [larsks/undocker#7]
After pulling busybox and running the following command :

![image](https://cloud.githubusercontent.com/assets/9333894/12520583/43cdafc4-c0fa-11e5-9465-20cee67bc3e8.png)

I get this error, what is wrong?

**Comment by larsks** [comment]
If I take a look at the current busybox image:

    $ docker pull busybox
    $ docker save busybox | undocker --list

It seems to work:

    docker.io/busybox: buildroot-2013.08.1 ubuntu-12.04 1-ubuntu 1 ubuntu-14.04 1.21.0-ubuntu ubuntu 1.23 1.23.2 latest 1.21-ubuntu buildroot-2014.02


Note however that the image name is "docker.io/busybox", not simply
"busybox".  To extract this:

    $ docker save busybox | undocker -o busybox docker.io/busybox

That works for me with the current code.

**Comment by gerdstolpmann** [comment]
I get the same error as the original poster. There is no archive member "repositories" in the tar file. Instead I see a "manifest.json". I guess it is a newer format.

**Comment by nizig** [comment]
`$ docker save 2084c1a1c9a0|undocker -i
Traceback (most recent call last):
  File "/usr/local/bin/undocker", line 11, in <module>
    load_entry_point('undocker==5', 'console_scripts', 'undocker')()
  File "/usr/local/lib/python2.7/dist-packages/undocker.py", line 81, in main
    repos = img.extractfile('repositories')
  File "/usr/lib/python2.7/tarfile.py", line 2143, in extractfile
    tarinfo = self.getmember(member)
  File "/usr/lib/python2.7/tarfile.py", line 1827, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'repositories' not found"
`

**Comment by dmick** [comment]
me too

**Comment by quinn** [comment]
I am also seeing a `manifest.json` file in the root of the archive. It seems to be of a different format than the one that this script expects.

**Comment by larsks** [comment]
Yes, it looks as if docker has changed the format of their images, probably at the same time they started computing sha256 checksums for image ids.  Looking at the new format and updating this tool is on my list of things to look at when I have some free time.  Pull requests are always appreciated as well!

**Comment by quinn** [comment]
I'll give it a try this morning and see if I can figure it out

**Comment by quinn** [comment]
when i run `docker save` i get a tar file that when extracted contains a file called `manifest.json` in the root of the archive which contains this:

```
[
    {
        "Config": "65e83cc2bf3021e9e1b5b6b785dffd1e3ad40484d972440ca39b85abb17f45ab.json",
        "RepoTags": null,
        "Layers": [
            "1b34e986a9bb5a5c0f5667e3430d9df1a79abdc04f117f99245eecd76c289ef8/layer.tar",
            "9fe171f1912016c611b4e8f5ec14c1aecb884bf8c0871bee3580005b3a761a4c/layer.tar",
            "2245ae966068d95d3cfe111f968e508c01254117f8cf38959915d32bb8de3c5b/layer.tar",
            "d7714d816b8fde61afd8e4e2bf08faaa7e55a593bd2845ca027394dd8a1ddddb/layer.tar",
            "a8b06d824dedd25a2ac8764803d1742b8a30be6d647b46281f308e059ef53942/layer.tar",
            "5ded7b22a544905fa85ffa2fad9be34fbf75a18bfee76cd409bc9aaeff37b363/layer.tar",
            "09dec5b66f36b092f5a2f7071a28ee06f8561fd718f6414ae35f5e72673397a8/layer.tar",
            "6a0f7ce4eb89879bdf3bbf31e4e2c2250408bc87aa1cb8cd6414f029521b1c75/layer.tar",
            "fd6c858f11ce1c22f019a899632573a0f5ae6bcdd40139e875ed2168fea0bb42/layer.tar",
            "8e91a7c830b4e9c2797134a15a6e585bf43bef2c5d623303405bb971c577d0c6/layer.tar",
            "3fe5e46391c06718eea3fe19db0ff977e88e43f6066030cfb852f9f99fe87c08/layer.tar",
            "d54f8ff99794238556b8d4ec5a432a71c1128b4e610af7fb8c769f3a79a9b7bc/layer.tar",
            "8f5153bd11a83191c9e668c079b141aea62d3bbd19196fad294758da34a2ccf5/layer.tar",
            "480cdeaee3162f70f079aa472f8a7092f8f9c774f76c36a57d818b98621f6a7b/layer.tar"
        ]
    }
]
```
For now I am going to make the assumption about this file that the root array only ever has one member, which is formatted like the above config. If the array would have more than one member I'm not sure what this would mean.

**Comment by quinn** [comment]
These changes seemed to allow me to extract the image: https://github.com/larsks/undocker/pull/14

**Comment by larsks** [comment]
fwiw, using docker 17.05.0-ce, I still don't see this problem.  Using the `busybox` image as an example, I see both `repositories` and `manifest.json`:

```
$ docker save busybox | tar -tf-
036a82c6d65f2fa43a13599661490be3fca1c3d6790814668d4e8c0213153b12/
036a82c6d65f2fa43a13599661490be3fca1c3d6790814668d4e8c0213153b12/VERSION
036a82c6d65f2fa43a13599661490be3fca1c3d6790814668d4e8c0213153b12/json
036a82c6d65f2fa43a13599661490be3fca1c3d6790814668d4e8c0213153b12/layer.tar
6ad733544a6317992a6fac4eb19fe1df577d4dec7529efec28a5bd0edad0fd30.json
manifest.json
repositories

```

For someone who is seeing this problem, I'm curious what version of docker you're working with, and whether the issue crops up for all images or only certain ones.

**Comment by april4** [comment]
looks like that undocker only work with 'REPOSITORY:TAG' form.
when I use this: 
docker save alpine | undocker -i --list -v
that works well.
But:
docker save ImageID | undocker -i --list -v
will raise:
KeyError: "filename 'repositories' not found"

**Comment by sushsada** [comment]
I'm runing into this too.

**Comment by dmick** [comment]
@april4's comment is correct; docker save <repo>:<tag> will output a 'repositories' file, but docker save <imageID> will not.  Also, manifest.json has a RepoTags element that, in the <repo>:<tag> output, contains <repo>:<tag>, but is empty when <imageID> is used.
